name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v7.0.0
        with: {python-version: "3.12"}
      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          python -m pip install -r requirements.txt -r requirements-dev.txt
      - name: Download LaLonde datasets
        run: python scripts/download_data.py
      - name: black
        run: black --check src/ tests/
      - name: isort
        run: isort --check-only src/ tests/ --profile black
      - name: flake8
        run: flake8 src/ tests/
      - name: mypy
        run: mypy src/
      - name: bandit
        run: bandit -r src/ -ll -ii
      - name: radon
        run: radon cc src/ -nc
      - name: interrogate
        run: interrogate src/ --fail-under=80
      - name: pip-audit
        run: pip-audit -r requirements.txt --ignore-vuln PYSEC-2024-274 --ignore-vuln PYSEC-2024-271 --ignore-vuln PYSEC-2024-277 --ignore-vuln PYSEC-2026-161 --ignore-vuln MAL-2026-4750
      - name: detect-secrets
        run: detect-secrets scan --baseline .secrets.baseline
      - name: pytest
        run: pytest tests/ -v --tb=short --cov=src --cov-fail-under=70
